### ISSUE TITLE
Create new config file for optional gossip local node configuration

### ISSUE THREAD

**Issue by timo0** [hashgraph/hedera-services#17075]
The config file should be in yaml format and should support lists. 

Eg:
```
gossip:
  interfaceBindings:
    - { "nodeId": 0, "hostname": "10.10.10.1", "port": 1234 }
    - { "nodeId": 0, "hostname": "10.10.10.2", "port": 1234 }
    - { "nodeId": 1, "hostname": "10.10.10.3", "port": 1234 }
    - { "nodeId": 4, "hostname": "2001:db8:3333:4444:5555:6666:7777:8888", "port": 1234 }
  randomStringValue: "random"
```
